name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: 🔍 Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your-dockerhub-username/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0

      - name: ☸️ Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: 🚀 Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-manifests/
